// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package main

import "time"

// DebounceBool debounces the input chan.
func DebounceBool(interval time.Duration, input chan bool) chan bool {
	output := make(chan bool)

	go func() {
		var i bool
		var ok bool

		for {
			i, ok = <-input

			if !ok {
				close(output)
				return
			}
		F:
			for {
				select {
				case i, ok = <-input:
					if !ok {
						close(output)
						return
					}
				case <-time.After(interval):
					output <- i
					break F
				}
			}
		}
	}()
	return output
}
